#!/bin/bash
if [ $# -ne 2 ]; then
	exit 1
fi
input=${1}
output=${2}
shopt -s nullglob
if [ -d "$1" ]; then
	for file in $input/*.{mp3,wav,ogg,flac}; do 
    		demucs --repo "model" -o "$output" -n 49469ca8 "$file"
	done
else
	demucs --repo "model" -o "$output" -n 49469ca8 "$input"
fi
exit 0
