#!/bin/bash
if [ $# -ne 0 ]; then
	exit 1
fi
version=$(pip list | grep -F demucs)
if [ "$version" == "" ]; then
	pip install demucs
fi
if [ ! -d "model" ] && [ $? -eq 0 ]; then
	mkdir "model"
	cd "model"
	pip install gdrive
	gdown 15eooSWblsJLwJ7EauxGrlmoSypgwG8ug
	cd ../
fi
exit 0
