#!/bin/bash
if [ $# -ne 0 ]; then
	exit 1
fi
if [ "$(pip list | grep -F demucs)" == "" ]; then
	pip install demucs
fi
if [ ! -d "model" ] && [ $? -eq 0 ]; then
	mkdir "model"
	cd "model"
	if [ "$(pip list | grep -F gdown)" == "" ]; then
		pip install gdown
	fi
	gdown 15eooSWblsJLwJ7EauxGrlmoSypgwG8ug
	cd ../
fi
exit 0
